### ISSUE TITLE
Death before low bound

### ISSUE THREAD

**Issue by Yapperyapps** [MysticCity/MinigamesAPI#241] opened 2017-04-07 21:26 UTC
I have a double layered map when when players fall off the first platform they die before reaching the second platform even though the low bound is set over 50 blocks below the last platform.

**Comment by PantallazoAzul** [comment] 2017-04-08 06:21
With what minigame are you experiencing this problem?
I have this problem with one own minigame. But not with Splegg, for example.

**Comment by mepeisen** [comment] 2017-04-08 06:39
The problem may be caused by some strange logic in minigames.
It tries to detect players falling out of the arena.

Edit config.yml and set config.die_below_bedrock_level to a proper numeric value. If set to a numeric value this will be the y coordinate where people are gonna lose the game.
This is not documented in wiki because it is a strange hack. In 2.0 this will change.

Does this help?

**Comment by Yapperyapps** [comment] 2017-04-10 22:00
Now instead the plugin makes the player lose the game by simply moving their mouse.

**Comment by Yapperyapps** [comment] 2017-04-10 22:10
It works now. /sp reload does not work for changing the bedrock level.

**Comment by Yapperyapps** [comment] 2017-04-10 22:12
Also just found an error But its probably only because Im using 1.8 
https://hastebin.com/ikuwiboxet.vbs

**Comment by mepeisen** [comment] 2017-04-11 06:07
Yes, online config reloading is not fully supported.
The "reload" feature is dropped in version 2. Instead there will be a more safe gui to edit configurations inline. And there will be a special arena mode called "maintenance". Changes to arenas are only allowed in this new mode.

I will check the error.
@me: v1.8R3:
10.04 23:09:00 [Server] INFO Caused by: java.lang.NoSuchFieldError: ENTITY_CHICKEN_EGG
10.04 23:09:00 [Server] INFO at com.comze_instancelabs.mgsplegg.Main.onProjectileLand(Main.java:232) ~[?:?]
10.04 23:09:00 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]

**Comment by PantallazoAzul** [comment] 2017-04-11 18:20
I still have this problem :( this affects a big arena in Splegg&Spleef only in the last platform, and affects a custom minigame I'm making :( this is my onMove method:
https://hastebin.com/wetoserulu.cs
I have this config:
  spectator:
    spectator_after_fall_or_death: false
    spectator_move_y_lock: false
  die_below_bedrock_level: -3

And arena bounds:
arenas:
  pizza1:
    bounds:
      high:
        world: tntrun
        location:
          x: -11.887622719099559
          y: 138.6540817122547
          z: -9.116579070957076
          yaw: -59.010315
          pitch: 90.0
      low:
        world: tntrun
        location:
          x: -32.28489476669113
          y: -1.53852891187742
          z: -28.978426915344933
          yaw: -40.200134
          pitch: -37.541344
    spawns:
      spawn0:
        world: tntrun
        location:
          x: -21.95547014200014
          y: 129.0
          z: -19.731968362752255
          yaw: -269.591
          pitch: -4.50906
    lobby:
      world: tntrun
      location:
        x: -7.5585948054592915
        y: 130.0
        z: -19.03164747098124
        yaw: -269.59235
        pitch: 3.749048

**Comment by mepeisen** [comment] 2017-04-12 04:37
1)
I must correct myself.

The numeric value in config does not contain absolute y coordinate. It is related to first spawn. Example: A value of 4 means: Lose if moving more than 4 blocks below first spawn.

So maybe you should simply increase the value to not die before reaching the last platform.

2)
the exception was fixed. It was related to play a sound once an egg hits something. Please verify with next build.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next two hours.

3)
Since setting your config value to a negative value this won't work. Should be fixed by setting it to a proper positive value.


*closed* If this does not help please respond. I will reopen the issue.

**Closed by mepeisen** 2017-04-12 04:37 UTC
Labels: Bug API/LIB, Bug Spleef / Splegg
