### ISSUE TITLE
Bug while restoring maps in skywars (I suspect "SmartReset")

### ISSUE THREAD

**Issue by sjoerd108** [MysticCity/MinigamesAPI#152] opened 2016-09-02 20:35 UTC
After players played one game of skywars the map is supposed to regenerate. However the plugin fails to do this fore some blocks leaving holes in the ground and random blocks from the previous game. Only /sw reset seems to resolve this issue however the server times outafter doing that.

Here is some info about my server:

- It has 4G of ram allocated to it.
- It is part of a bungee network (The plugin however is not configured that way)
- The server currently uses Java 1.8.0_102 on windows
- We are running on spigot 1.10.2

**Comment by mepeisen** [comment] 2016-09-03 04:52
which version of minigames lib/ skywars are you using?

**Comment by sjoerd108** [comment] 2016-09-03 09:46
I am using for both plugins (the lib and skywars) the latest downloadable version. (1.14.11)

**Comment by mepeisen** [comment] 2016-09-03 14:04
Can you set debugging to true (see  minigames lib options.yml) and send me al log of a corrupt game including reset?
The log will be large. You can send a zip file to mep_eisen@web.de

Please include the block loccations that are missed during reset (see with F3).

**Comment by sjoerd108** [comment] 2016-09-03 17:15
I send you an email.

**Comment by mepeisen** [comment] 2016-09-03 17:32
Can you create a screenshot from your arena? How many blocks of air are between the platforms?

**Comment by sjoerd108** [comment] 2016-09-03 18:00
There are 18 blocks of air between the middle island and the islands that are on a straight line with the middle island. The islands on a diagonal line are 23 blocks from the middle. Here are some screenshots of the map without artifacts to clarify:
![2016-09-03_19 51 08](https://cloud.githubusercontent.com/assets/17080530/18226747/e9ed8650-7210-11e6-93c7-d21e5bdc6b9a.png)
![2016-09-03_19 59 28](https://cloud.githubusercontent.com/assets/17080530/18226755/0bef6ec6-7211-11e6-9fc3-507e11ae6b0a.png)

**Comment by mepeisen** [comment] 2016-09-08 06:18
Can you send me a World guard schematic?  Mep_eisen@web.de 
Will delete it After fixing the bug

**Comment by mepeisen** [comment] 2016-09-08 06:19
World edit schematic. Sry 😀

**Comment by sjoerd108** [comment] 2016-09-08 06:38
No problem I will do it when I get home.

**Comment by sjoerd108** [comment] 2016-09-10 11:42
Did you recieve the map per E-Mail correctly?

**Comment by mepeisen** [comment] 2016-09-10 11:56
yes. will test it the next hours :-)

**Comment by Taronyuu** [comment] 2016-09-11 12:04
This is probably not related to the SkyWars plugin, I'm having the same problem while developing a different game using this library.

Quick example: this game removes blocks under the player feets while running. (Snow -> packed ice -> ice -> air). Every game a few blocks are not reset back to snow but stay ice or air. 
Screenshot before: https://snapr.pw/i/0292f2e3f2.png
Screenshot after: https://snapr.pw/i/96db356c53.png
Log: http://hastebin.com/erizihuyer.rb
I tried executing the reset() function again after 5 seconds to make sure it wasn't my code that was still running. But that did not help either.

**Comment by mepeisen** [comment] 2016-09-11 12:23
@Taronyuu: are you adding the changed blocks manually to smart reset?

**Comment by Taronyuu** [comment] 2016-09-11 12:41
I did not, doing that seems to have fixed the problem. :)

Weird however that about 90% of all changed blocks where restored but a few where not. Can you explain when they are added automatically and when they are not?

**Comment by mepeisen** [comment] 2016-09-11 14:28
In 2.0 this will change.
It is hard do fix it for know because there is too much logic inside the event listeners. I tried to change it but this brkome some of the existing games.

There is one overall rule: Blocks outside the arena bounds are NOT added automatically. And they won't be added in 2.0 too.

So there are still blocks that are making problems for you?

@sjoerd108:
Your problems maybe caused by physics (sand). I am still researching. Are you using sand? But are you able to use some non-physic block, for example sandstone instead of sand.

The server timeout may be caused by your arena size. Will be fixed in 2.0

**Comment by sjoerd108** [comment] 2016-09-11 14:32
Yeah the full arena reset crash is caused by the size of the arena. I can use sandstone instead of sand but how about water or lava then?

**Comment by mepeisen** [comment] 2016-09-11 14:47
Do not yet use water or lava. Using sandstone It is only a test. If it works I can research what is happening to sand and why it is not cworking fine.

**Comment by mepeisen** [comment] 2016-10-16 08:34
I fixed an issue related to blocks the users are placing. Please retry with latest snapshot.
The only remaining problem should be related to lava/water.
Can you verify?
http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.12-SNAPSHOT/Minigames-All-1.14.12-20161016.083234-5-bin.zip

**Comment by sjoerd108** [comment] 2016-10-25 21:45
It appears to work, Tested the same map (I replaced the water with sand) all placed and broken blocks got reset even the cactus.

I am sorry for my late reply.

**Comment by mepeisen** [comment] 2016-10-29 11:16
thx. will close the bug.

**Closed by mepeisen** 2016-10-29 11:16 UTC
Labels: Bug API/LIB
