### ISSUE TITLE
Several java exceptions

### ISSUE THREAD

**Issue by WyRe** [MysticCity/MinigamesAPI#230] opened 2017-03-23 02:46 UTC
I'm getting several exceptions which I don't know if could be related with a few issues what I'm experiencing, like limited movement when people are death and invisible, for instance. These are the exceptions:

```
[03:36:55] [Server thread/WARN]: [MinigamesLib] Failed playing fakebed effect
java.lang.NoSuchMethodException: net.minecraft.server.v1_11_R1.BlockPosition.<init>(java.lang.Integer, java.lang.Integer, java.lang.Integer)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_121]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_121]
	at com.comze_instancelabs.minigamesapi.Effects.playFakeBed(Effects.java:132) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.Effects.playFakeBed(Effects.java:91) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena.spectateRaw(Arena.java:1475) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena.spectateGame(Arena.java:1426) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena.spectate(Arena.java:1461) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.mgskywars.IArena.spectate(IArena.java:56) [MGSkyWars-Plugin-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.ArenaListener.onMove(ArenaListener.java:939) [MinigamesLib-1.14.15.jar:?]
	at sun.reflect.GeneratedMethodAccessor727.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:615) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[03:38:02] [Server thread/WARN]: [MinigamesLib] Failed playing fakebed effect
java.lang.NoSuchMethodException: net.minecraft.server.v1_11_R1.BlockPosition.<init>(java.lang.Integer, java.lang.Integer, java.lang.Integer)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_121]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_121]
	at com.comze_instancelabs.minigamesapi.Effects.playFakeBed(Effects.java:132) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.Effects.playFakeBed(Effects.java:91) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena.spectateRaw(Arena.java:1475) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena.spectateGame(Arena.java:1426) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena.spectate(Arena.java:1461) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.mgskywars.IArena.spectate(IArena.java:56) [MGSkyWars-Plugin-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.ArenaListener.onMove(ArenaListener.java:939) [MinigamesLib-1.14.15.jar:?]
	at sun.reflect.GeneratedMethodAccessor727.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:615) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[03:38:30] [Server thread/WARN]: [MinigamesLib] Failed playing fakebed effect
java.lang.NoSuchMethodException: net.minecraft.server.v1_11_R1.BlockPosition.<init>(java.lang.Integer, java.lang.Integer, java.lang.Integer)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_121]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_121]
	at com.comze_instancelabs.minigamesapi.Effects.playFakeBed(Effects.java:132) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.Effects.playFakeBed(Effects.java:91) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena.spectateRaw(Arena.java:1475) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena.spectateGame(Arena.java:1426) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.Arena.spectate(Arena.java:1461) [MinigamesLib-1.14.15.jar:?]
	at com.comze_instancelabs.mgskywars.IArena.spectate(IArena.java:56) [MGSkyWars-Plugin-1.14.15.jar:?]
	at com.comze_instancelabs.minigamesapi.ArenaListener.onMove(ArenaListener.java:939) [MinigamesLib-1.14.15.jar:?]
	at sun.reflect.GeneratedMethodAccessor727.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:615) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.1.11.2.jar:git-Spigot-96235ab-257d6cd]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

```

I am in 1.11.2 Spigot version. Thank you guys and sorry if this is obviousness or is already reported.

**Comment by mepeisen** [comment] 2017-03-23 06:55
I will review the bug this weekend.

The exception may cause some of the problems. What exactly is going wrong when dying?

**Comment by WyRe** [comment] 2017-03-23 15:54
Well, basically when somebody death and he pass to spectator state, he can't move vertically, he only can move horizontally.

**Comment by PantallazoAzul** [comment] 2017-03-23 20:24
It's a config option, 
  spectator:
    spectator_after_fall_or_death: true
    spectator_move_y_lock: true

Set it to false.
    spectator_move_y_lock: false

**Comment by WyRe** [comment] 2017-03-23 22:55
I don't see that string in my config.yml located at plugins/MinigamesLib

**Comment by WyRe** [comment] 2017-03-23 23:43
@PantallazoAzul I've trying to modify this value but it changes to true when I restart my server.

**Comment by PantallazoAzul** [comment] 2017-03-24 01:37
Change it and do /sw reload (you have to modify your config.yml of /MGSkyWars/)

**Comment by WyRe** [comment] 2017-03-27 12:41
I'm experiencing a few bugs what I don't know if could be related with this java exceptions but I will publish in here:

- Hide players after play in skywars arena; after play in any skywars arena some player seems to be invisible en world map, even pressing tab they aren't listed.
- Bugged arena signal; sometimes a signal gets bugged in red state and I need remove it and replace again.
- Wrong players number; often the signals shows a number of players when really there is anybody playing in there.

Thank you and I hope have been helpful.

**Comment by mepeisen** [comment] 2017-04-12 04:26
> - Hide players after play in skywars arena; after play in any skywars arena some player seems to be invisible en world map, even pressing tab they aren't listed. It is necessary reconnect the server to see them and get them listed.

Exceptions are now fixed and this should fix the hide problem too. Please retry with latest snapshot.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next two hours.

> Bugged arena signal; sometimes a signal gets bugged in red state and I need remove it and replace again.
> Wrong players number; often the signals shows a number of players when really there is not anybody playing in there.

Can you reproduce the problem? What is happening if signal gets broken? Are you using multiple servers (bungeecord network)?

**Comment by WyRe** [comment] 2017-04-12 12:07
No, I'm not using multiple servers, If the signal gets broken and replaced the problem is fixed, It happens when people finish a match and they come out of the arena. The signal doesn't show available area or real people number inside.

**Comment by WyRe** [comment] 2017-04-21 18:40
Now I'm getting that other ones. 

```
[20:38:31 INFO]: [MinigamesLib] retrying failed block Location{world=CraftWorld{name=SkywarsMap1vs1v2},x=0.0,y=122.0,z=14.0,pitch=0.0,yaw=0.0}
[20:38:31 WARN]: [MinigamesLib] Task #1207807 for MinigamesLib v1.14.16-20170412.063652 generated an exception
java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventory.setContents(CraftInventory.java:82) ~[spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at com.comze_instancelabs.minigamesapi.SmartReset.lambda$run$0(SmartReset.java:287) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[20:38:31 INFO]: [MinigamesLib] retrying failed block Location{world=CraftWorld{name=SkywarsMap1vs1v2},x=0.0,y=122.0,z=14.0,pitch=0.0,yaw=0.0}
[20:38:31 WARN]: [MinigamesLib] Task #1207820 for MinigamesLib v1.14.16-20170412.063652 generated an exception
java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventory.setContents(CraftInventory.java:82) ~[spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at com.comze_instancelabs.minigamesapi.SmartReset.lambda$run$0(SmartReset.java:287) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[20:38:31 INFO]: [MinigamesLib] retrying failed block Location{world=CraftWorld{name=SkywarsMap1vs1v2},x=0.0,y=122.0,z=14.0,pitch=0.0,yaw=0.0}
[20:38:31 WARN]: [MinigamesLib] Task #1207821 for MinigamesLib v1.14.16-20170412.063652 generated an exception
java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventory.setContents(CraftInventory.java:82) ~[spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at com.comze_instancelabs.minigamesapi.SmartReset.lambda$run$0(SmartReset.java:287) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.1.11.2.jar:git-Spigot-54ec0b8-e04a179]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by mepeisen** [comment] 2017-04-22 09:16
Are there exceptions before?

**Comment by WyRe** [comment] 2017-04-22 11:43
I don't think; i've reviewed the last logs and I didn't see any exception more:

```
2017-04-19-2.log:[17:00:09] [Server thread/INFO]: [MinigamesLib] Loading MinigamesLib v1.14.16-20170412.063652
2017-04-19-2.log:[17:00:52] [Server thread/INFO]: [MinigamesLib] Enabling MinigamesLib v1.14.16-20170412.063652
2017-04-19-2.log:[17:00:52] [Server thread/INFO]: [MinigamesLib] §c§lLoaded MinigamesAPI. We're on V1_11_R1.
2017-04-19-2.log:[17:00:56] [Server thread/INFO]: [MinigamesLib] Found 3 arenas.
2017-04-19-2.log:[17:28:55] [Server thread/INFO]: [MinigamesLib] Disabling MinigamesLib v1.14.16-20170412.063652
2017-04-19-3.log:[17:29:09] [Server thread/INFO]: [MinigamesLib] Loading MinigamesLib v1.14.16-20170412.063652
2017-04-19-3.log:[17:29:30] [Server thread/INFO]: [MinigamesLib] Enabling MinigamesLib v1.14.16-20170412.063652
2017-04-19-3.log:[17:29:30] [Server thread/INFO]: [MinigamesLib] §c§lLoaded MinigamesAPI. We're on V1_11_R1.
2017-04-19-3.log:[17:29:34] [Server thread/INFO]: [MinigamesLib] Found 3 arenas.
2017-04-19-3.log:[17:30:31] [Server thread/INFO]: [MinigamesLib] Disabling MinigamesLib v1.14.16-20170412.063652
2017-04-19-4.log:[17:31:45] [Server thread/INFO]: [MinigamesLib] Loading MinigamesLib v1.14.16-20170412.063652
2017-04-19-4.log:[17:32:06] [Server thread/INFO]: [MinigamesLib] Enabling MinigamesLib v1.14.16-20170412.063652
2017-04-19-4.log:[17:32:06] [Server thread/INFO]: [MinigamesLib] §c§lLoaded MinigamesAPI. We're on V1_11_R1.
2017-04-19-4.log:[17:32:10] [Server thread/INFO]: [MinigamesLib] Found 3 arenas.
2017-04-21-1.log:[20:38:31] [Server thread/INFO]: [MinigamesLib] retrying failed block Location{world=CraftWorld{name=SkywarsMap1vs1v2},x=0.0,y=122.0,z=14.0,pitch=0.0,yaw=0.0}
2017-04-21-1.log:[20:38:31] [Server thread/WARN]: [MinigamesLib] Task #1207807 for MinigamesLib v1.14.16-20170412.063652 generated an exception
2017-04-21-1.log:	at com.comze_instancelabs.minigamesapi.SmartReset.lambda$run$0(SmartReset.java:287) ~[?:?]
2017-04-21-1.log:[20:38:31] [Server thread/INFO]: [MinigamesLib] retrying failed block Location{world=CraftWorld{name=SkywarsMap1vs1v2},x=0.0,y=122.0,z=14.0,pitch=0.0,yaw=0.0}
2017-04-21-1.log:[20:38:31] [Server thread/WARN]: [MinigamesLib] Task #1207820 for MinigamesLib v1.14.16-20170412.063652 generated an exception
2017-04-21-1.log:	at com.comze_instancelabs.minigamesapi.SmartReset.lambda$run$0(SmartReset.java:287) ~[?:?]
2017-04-21-1.log:[20:38:31] [Server thread/INFO]: [MinigamesLib] retrying failed block Location{world=CraftWorld{name=SkywarsMap1vs1v2},x=0.0,y=122.0,z=14.0,pitch=0.0,yaw=0.0}
2017-04-21-1.log:[20:38:31] [Server thread/WARN]: [MinigamesLib] Task #1207821 for MinigamesLib v1.14.16-20170412.063652 generated an exception
2017-04-21-1.log:	at com.comze_instancelabs.minigamesapi.SmartReset.lambda$run$0(SmartReset.java:287) ~[?:?]
```

**Comment by mepeisen** [comment] 2017-05-08 05:20
Moved to 1.14.17. I will Play around with chests in arenas the next weeks.

**Comment by mepeisen** [comment] 2017-06-11 17:06
I fixed some smart reset handlings for chests.
Hope that I got your problem too because I cannot reproduce it.
Even I cannot verify the null pointer exception on your line of code in craftbukkit.... Do you have a customized build of spigot? Any special with chests on your battlefield?


Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.

**Closed by mepeisen** 2017-06-11 17:06 UTC
Labels: Bug API/LIB
