### ISSUE TITLE
Minigame Conquest  Extreme lag

### ISSUE THREAD

**Issue by Jacobnordvall** [MysticCity/MinigamesAPI#209] opened 2017-01-30 15:19 UTC
[16:15:10] [Server thread/INFO]: Sallad_Ass issued server command: /cq join
[16:15:29] [Server thread/WARN]: [LagMonitor] Plugin MGConquer is performing a blocking action to socket://api.mojang.com:443 on the main thread This could be a performance hit. Such actions should be handled async from the main thread Report it to the plugin author
[16:15:29] [Server thread/WARN]: [LagMonitor] The following exception is not an error. It's a hint for the plugin developer to find the source of the blocking action. LagMonitor doesn't prevent this action. It just warns you
java.lang.Exception
	at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:40) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_91]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_91]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:1.8.0_91]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[?:1.8.0_91]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source) ~[?:1.8.0_91]
	at com.mojang.authlib.HttpAuthenticationService.performPostRequest(HttpAuthenticationService.java:77) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:66) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:54) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.UserCache.a(UserCache.java:88) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.UserCache.getProfile(UserCache.java:157) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.getOfflinePlayer(CraftServer.java:1305) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:731) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at com.comze_instancelabs.conquer.IArenaScoreboard.updateScoreboard(IArenaScoreboard.java:43) ~[?:?]
	at com.comze_instancelabs.conquer.IArena.start(IArena.java:116) ~[?:?]
	at com.comze_instancelabs.minigamesapi.Arena.lambda$null$17(Arena.java:1663) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[16:15:31] [Server thread/WARN]: Sallad_Ass moved too quickly! 72.11183911733406,-2.0625,-328.0320852606387
[16:16:13] [Server thread/INFO]: Sallad_Ass issued server command: /leave
[16:16:40] [Server thread/INFO]: [MGOITC] [arena:Arena1] started

**Comment by mepeisen** [comment] 2017-01-30 15:45
closed as duplicate of #207

**Closed by mepeisen** 2017-01-30 15:45 UTC

**Comment by Jacobnordvall** [comment] 2017-01-31 15:46
no this is one of your other minigames! :(((

**Comment by mepeisen** [comment] 2017-01-31 16:09
It is not really the minigame itself that causes the problems. There are some things in the underlying minigames library. I will have a look at performance and yes, I will check which minigames are infected, :-)

**Comment by Jacobnordvall** [comment] 2017-01-31 17:40
thx :D always wonderful too be able to help this lib get better ;D and its even better that you acturaly respond to suggestions and bug repports :P not many developers are this cind yo kno. :)
